/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JPanel;



/**
 *
 * @author CDM-51
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final Login login = new Login();
    /**
     * Creates new form MenuUsuario
     */
    public MenuPrincipal() {
        initComponents();
        jLabelBienvenidaUsuario.setText("BIENVENIDO/A - " + login.getUsuario().getNombreUsuario());
        esGerente();
        alternarVisualizacionMenu();
        
    }

     /**
     * Al sólo existir dos categorías de usuario, evaluamos si el usuario
     * logeado actualmente, es gerente.
     *
     */
    public static boolean esGerente() {
        String categoriaUsuario = "Gerente";
        String categoriaUsuarioActual = login.getUsuario().getCategoriaUsuario();
        return categoriaUsuarioActual.equals(categoriaUsuario);
    }
    
    /**
     * Muestra los botones que correspondan acorde a la categoría del usuario.
     */
    private void alternarVisualizacionMenu() {
        if (esGerente()) {
            jLabelTextoUsuario.setVisible(true);
            btnUsuario.setVisible(true);
        } else {
            jLabelTextoUsuario.setVisible(false);
            btnUsuario.setVisible(false);
        }
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSGradientPanel1 = new LIB.FSGradientPanel();
        btnResevas = new LIB.FSButtonMD();
        btnBusqueda = new LIB.FSButtonMD();
        jLabelTextoUsuario = new javax.swing.JLabel();
        btnUsuario = new LIB.FSButtonMD();
        jLabel5 = new javax.swing.JLabel();
        jPanelRound1 = new LIB.JPanelRound();
        jLabel3 = new javax.swing.JLabel();
        fSGradientPanel2 = new LIB.FSGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabelBienvenidaUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fSGradientPanel1.setFSEndColor(new java.awt.Color(102, 102, 102));
        fSGradientPanel1.setFSStartColor(new java.awt.Color(0, 0, 51));
        fSGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResevas.setText("RESERVAS");
        btnResevas.setColorHover(new java.awt.Color(0, 153, 0));
        btnResevas.setColorNormal(new java.awt.Color(51, 51, 51));
        btnResevas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResevasMouseClicked(evt);
            }
        });
        btnResevas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResevasActionPerformed(evt);
            }
        });
        fSGradientPanel1.add(btnResevas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 229, 65));

        btnBusqueda.setText("BUSQUEDA");
        btnBusqueda.setColorHover(new java.awt.Color(0, 153, 0));
        btnBusqueda.setColorNormal(new java.awt.Color(51, 51, 51));
        btnBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseClicked(evt);
            }
        });
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        fSGradientPanel1.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 65));

        jLabelTextoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTextoUsuario.setForeground(new java.awt.Color(12, 138, 199));
        jLabelTextoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fSGradientPanel1.add(jLabelTextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 409, 100, 14));

        btnUsuario.setText("USUARIO");
        btnUsuario.setColorHover(new java.awt.Color(0, 153, 0));
        btnUsuario.setColorNormal(new java.awt.Color(51, 51, 51));
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
        });
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        fSGradientPanel1.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 65));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        fSGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 627, -1, 40));

        jPanelRound1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        jPanelRound1.setColorPrimario(new java.awt.Color(255, 255, 0));
        jPanelRound1.setColorSecundario(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logohotel.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        fSGradientPanel1.add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 150));

        getContentPane().add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 690));

        fSGradientPanel2.setFSEndColor(new java.awt.Color(102, 0, 102));
        fSGradientPanel2.setFSStartColor(new java.awt.Color(204, 204, 0));
        fSGradientPanel2.setPreferredSize(new java.awt.Dimension(741, 469));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU USUARIO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fSGradientPanel2Layout = new javax.swing.GroupLayout(fSGradientPanel2);
        fSGradientPanel2.setLayout(fSGradientPanel2Layout);
        fSGradientPanel2Layout.setHorizontalGroup(
            fSGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fSGradientPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fSGradientPanel2Layout.setVerticalGroup(
            fSGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fSGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(fSGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1050, 70));

        content.setBackground(new java.awt.Color(153, 153, 153));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBienvenidaUsuario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelBienvenidaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBienvenidaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        content.add(jLabelBienvenidaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 740, 150));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/third.jpg"))); // NOI18N
        content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 1050, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Mensaje.confirmarSalida(evt);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnResevasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResevasMouseClicked
       evt.consume();
       // this.dispose();
        Reservas reservas = new Reservas();
        reservas.setVisible(true);

    }//GEN-LAST:event_btnResevasMouseClicked

    private void btnBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseClicked
        evt.consume();
       // this.dispose();
        Busqueda busqueda = new Busqueda();
        busqueda.setVisible(true);

    }//GEN-LAST:event_btnBusquedaMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        evt.consume();
        this.dispose();
        Inicio menuPrincipal = new Inicio();
        menuPrincipal.setVisible(true);
        menuPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
        evt.consume();
        
        RegistrarUsuario registrarUsuario = new RegistrarUsuario();
        registrarUsuario.setVisible(true);

    }//GEN-LAST:event_btnUsuarioMouseClicked

    private void btnResevasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResevasActionPerformed
       Reservas p1 = new Reservas();
       showPanel(p1);
    }//GEN-LAST:event_btnResevasActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
       Busqueda p2 = new Busqueda();
       showPanel(p2);
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
       RegistrarUsuario p3 = new RegistrarUsuario();
       showPanel(p3);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnBusqueda;
    private LIB.FSButtonMD btnResevas;
    private LIB.FSButtonMD btnUsuario;
    private javax.swing.JPanel content;
    private LIB.FSGradientPanel fSGradientPanel1;
    private LIB.FSGradientPanel fSGradientPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBienvenidaUsuario;
    private javax.swing.JLabel jLabelTextoUsuario;
    private LIB.JPanelRound jPanelRound1;
    // End of variables declaration//GEN-END:variables

private void showPanel(JPanel p){
        p.setSize(1000, 550);
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        content.revalidate();
        content.repaint();
    }
     

}
    

   


