/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import controller.UsuarioController;
import modelo.Usuario;
import util.ValidarFormulariosUtil;
/**
 *
 * @author CDM-51
 */
public class RegistrarUsuario extends javax.swing.JPanel {

    private final UsuarioController usuarioController;
    /**
     * Creates new form Login1
     */
    public RegistrarUsuario() {
        initComponents();
        this.usuarioController = new UsuarioController();          
    }
    
    
     private void guardarUsuario() {
        String nombreUsuario = campoNombreUsuario.getText();
        if (ValidarFormulariosUtil.esFormularioUsuarioValido(nombreUsuario, seleccionCategoriaUsuario, campoPassword)) {
            Usuario usuario = new Usuario(
                    campoNombreUsuario.getText(),
                    seleccionCategoriaUsuario.getSelectedItem().toString(),
                    String.valueOf(campoPassword.getPassword())
            );
            this.usuarioController.guardar(usuario);
            JOptionPane.showMessageDialog(
                    null,
                    "Usuario guardado éxitosamente.",
                    "Guardado éxitoso.",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }

    public void reestablecerCampos() {
        campoNombreUsuario.setText("");
        seleccionCategoriaUsuario.setSelectedIndex(0);
        campoPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound1 = new LIB.JPanelRound();
        jPanelRound2 = new LIB.JPanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        jLabelCategoria = new javax.swing.JLabel();
        seleccionCategoriaUsuario = new javax.swing.JComboBox<>();
        jLabelPassword = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        btnGuardar = new LIB.FSButtonMD();
        btnCancelar = new LIB.FSButtonMD();
        jLabelImagenFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound1.setColorPrimario(new java.awt.Color(102, 102, 102));
        jPanelRound1.setColorSecundario(new java.awt.Color(0, 0, 51));

        jPanelRound2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        jPanelRound2.setColorPrimario(new java.awt.Color(102, 102, 102));
        jPanelRound2.setColorSecundario(new java.awt.Color(51, 51, 51));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login_icon_176905.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo usuario.png"))); // NOI18N
        jLabelNombreUsuario.setText("   INGRESE NUEVO USUARIO");

        campoNombreUsuario.setBackground(new java.awt.Color(102, 102, 102));
        campoNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        campoNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNombreUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));

        jLabelCategoria.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categoria.png"))); // NOI18N
        jLabelCategoria.setText("   CATEGORIA USUSARIO");

        seleccionCategoriaUsuario.setBackground(new java.awt.Color(102, 102, 102));
        seleccionCategoriaUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seleccionCategoriaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        seleccionCategoriaUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija la categoría de Usuario", "Gerente", " Recepcionista" }));
        seleccionCategoriaUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contraseña.png"))); // NOI18N
        jLabelPassword.setText("   INGRESE CONTRASEÑA");

        campoPassword.setBackground(new java.awt.Color(102, 102, 102));
        campoPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        campoPassword.setForeground(new java.awt.Color(255, 255, 255));
        campoPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPassword)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNombreUsuario)
                            .addComponent(seleccionCategoriaUsuario, 0, 358, Short.MAX_VALUE)
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCategoria)
                                    .addComponent(jLabelNombreUsuario))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionCategoriaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 370, 530));

        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("   GUARDAR");
        btnGuardar.setColorNormal(new java.awt.Color(51, 51, 51));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 130, -1));

        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar_1.png"))); // NOI18N
        btnCancelar.setText("   CANCELAR");
        btnCancelar.setColorHover(new java.awt.Color(0, 153, 153));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 130, -1));

        jLabelImagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/third.jpg"))); // NOI18N
        jLabelImagenFondo.setPreferredSize(new java.awt.Dimension(1050, 480));
        add(jLabelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        evt.consume();
        guardarUsuario();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        evt.consume();
        Mensaje.cancelarRegistro(evt, this);
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnCancelar;
    private LIB.FSButtonMD btnGuardar;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelImagenFondo;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelPassword;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    private javax.swing.JComboBox<String> seleccionCategoriaUsuario;
    // End of variables declaration//GEN-END:variables

    void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
